GET http://localhost:3000/players/
###
POST http://localhost:3000/players/
###
GET https://localhost:3000/players/:playerId/
###
PUT https://localhost:3000/players/:playerId/
###

DELETE https://localhost:3000/players/:playerId/